from django.conf.urls import *

urlpatterns = patterns('analisis.analisis.views',
    #######################################################
    url(r'^inicio/$', 'indexnuevo', name='indexnuevo'),
    url(r'^consulta/$', 'consulta', name='consulta'),
    #######################################################
	url(r'^$', 'inicio', name="inicio"),
    #url(r'^salidas/$', 'post', name='salidas'),
    url(r'^organizaciones/$', 'salida1', name='organizaciones'),
    url(r'^proyectos-sector/$', 'salida2', name='proyectos-sector'),
    url(r'^proyectos-tema/$', 'salida3', name='proyectos-tema'),
    url(r'^impactos-sector/$', 'salida4', name='impactos-sector'),
    url(r'^impactos-tema/$', 'salida5', name='impactos-tema'),
    url(r'^impactos-beneficiarios/$', 'salida5b', name='impactos-beneficiarios'),
    url(r'^innovaciones-sector/$', 'salida6', name='innovaciones-sector'),
    url(r'^innovaciones-tema/$', 'salida7', name='innovaciones-tema'),
    url(r'^temas-sector/$', 'salida13', name='temas-sector'),
    url(r'^aliados-roles/$', 'salida8', name='aliados-roles'),
    url(r'^sectores-aliados/$', 'salida9', name='sectores-aliados'),
    url(r'^relaciones-sectores/$', 'salida10', name='relaciones-sectores'),
    #url(r'^salida11/$', 'salida11', name='salida11'),
    #url(r'^salida12/$', 'salida12', name='salida12'),
    url(r'^innovaciones-futuras-sector/$', 'salida14', name='innovaciones-futuras-sector'),
    url(r'^innovaciones-futuras-tema/$', 'salida15', name='innovaciones-futuras-tema'),
    url(r'^socio-potenciales-sector/$', 'salida16', name='salida16'),
    url(r'^socios-tiempo/$', 'salida17', name='socios-tiempo'),
    url(r'^fuentes-aprendizaje/$', 'salida18', name='fuentes-aprendizaje'),
    url(r'^informacion-necesaria/$', 'salida19', name='informacion-necesaria'),
    url(r'^limitaciones/$', 'salida20', name='limitaciones'),

    url(r'^ajax/fechas/$', 'get_fecha', name='get_fecha'),
    url(r'^ajax/sitioaccion/$', 'get_sitio_accion', name='get_sitio_accion'),
    url(r'^ajax/plataforma/$', 'get_plataforma', name='get_plataforma'),
    )