from django.conf.urls import *

urlpatterns = patterns('analysis.analysis.views',
	url(r'^$', 'inicio', name="inicio"),
    #url(r'^salidas/$', 'post', name='salidas'),
    url(r'^organizations/$', 'output1', name='organizations'),
    url(r'^projects-by-sector/$', 'output2', name='projects-by-sector'),
    url(r'^projects-by-theme/$', 'output3', name='projects-by-theme'),
    url(r'^impacts-by-sector/$', 'output4', name='impacts-by-sector'),
    url(r'^impacts-by-theme/$', 'output5', name='impacts-by-theme'),
    url(r'^impacts-by-beneficiaries/$', 'output5b', name='impacts-by-beneficiaries'),
    url(r'^innovations-by-sector/$', 'output6', name='innovations-by-sector'),
    url(r'^innovations-by-theme/$', 'output7', name='innovations-by-theme'),
    url(r'^partnerships-and-roles/$', 'output8', name='partnerships-and-roles'),
    url(r'^sectors-and-allies/$', 'output9', name='sectors-and-allies'),
    url(r'^relations-sectors/$', 'output10', name='relations-sectors'),
    # url(r'^output11/$', 'output11', name='output11'),
    # url(r'^output12/$', 'output12', name='output12'),
    url(r'^themes-sector/$', 'output13', name='themes-sector'),
    url(r'^innovations-by-sector/$', 'output14', name='innovations-by-sector'),
    url(r'^innovations-by-theme/$', 'output15', name='innovations-by-theme'),
    url(r'^potential-partners-by-sector/$', 'output16', name='potential-partners-by-sector'),
    url(r'^output17/$', 'output17', name='output17'),
    url(r'^output18/$', 'output18', name='output18'),
    url(r'^output19/$', 'output19', name='output19'),
    url(r'^output20/$', 'output20', name='output20'),
    url(r'^ajax/fechas/$', 'get_fecha', name='get_fecha'),
    
    )