from django.conf.urls import *

urlpatterns = patterns('analysis.analysis.views',
	url(r'^$', 'inicio', name="inicio"),
    #url(r'^salidas/$', 'post', name='salidas'),
    url(r'^organizations/$', 'output1', name='organizations'),
    url(r'^projects-by-sector/$', 'output2', name='projects-by-sector'),
    url(r'^projects-by-theme/$', 'output3', name='projects-by-theme'),
    url(r'^impacts-by-sector/$', 'output4', name='impacts-by-sector'),
    url(r'^impacts-by-theme/$', 'output5', name='impacts-by-theme'),
    url(r'^impacts-by-beneficiaries/$', 'output5b', name='impacts-by-beneficiaries'),
    url(r'^innovations-by-sector/$', 'output6', name='innovations-by-sector'),
    url(r'^innovations-by-theme/$', 'output7', name='innovations-by-theme'),
    url(r'^partnerships-and-roles/$', 'output8', name='partnerships-and-roles'),
    url(r'^sectors-and-allies/$', 'output9', name='sectors-and-allies'),
    url(r'^relations-sectors/$', 'output10', name='relations-sectors'),
    # url(r'^output11/$', 'output11', name='output11'),
    # url(r'^output12/$', 'output12', name='output12'),
    url(r'^themes-sector/$', 'output13', name='themes-sector'),
    url(r'^future-innovations-by-sector/$', 'output14', name='innovations-by-sector'),
    url(r'^future-innovations-by-theme/$', 'output15', name='innovations-by-theme'),
    url(r'^potential-partners-by-sector/$', 'output16', name='potential-partners-by-sector'),
    url(r'^partners-in-time/$', 'output17', name='partners-in-time'),
    url(r'^learning-sources/$', 'output18', name='learning-sources'),
    url(r'^needed-information/$', 'output19', name='needed-information'),
    url(r'^limitations/$', 'output20', name='limitations'), 
    
    url(r'^ajax/fechas/$', 'get_fecha', name='get_fecha'),
    url(r'^ajax/sitioaccion/$', 'get_sitio_accion', name='get_sitio_accion'),
    url(r'^ajax/plataforma/$', 'get_plataforma', name='get_plataforma'),
    
    )